config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :restaurants, shallow: true do
    resources :reviews do
      resources :endorsements
  end
end
  # The priority is based upon order of creatio n: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root "restaurants#index"

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  belongs_to :user
  has_many :reviews,
        -> { extending WithUserAssociationExtension },
        dependent: :destroy
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :name, length: { minimum: 3 }, uniqueness: true



  def average_rating
    return 'N/A' if reviews.none?
    # reviews.average(:rating)
    reviews.inject(0) {|memo, review| memo + review.rating} / reviews.size

  end

end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :restaurant
  has_many :endorsements
  validates :rating, inclusion: (1..5)
  validates :user, uniqueness: { scope: :restaurant, message: "You have reviewed this restaurant already" }

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :restaurants
  has_many :reviews, dependent: :destroy
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def has_reviewed?(restaurant)
    reviewed_restaurants.include? restaurant
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/models/with_user_association_extension.rb
module WithUserAssociationExtension


  def create_with_user(attributes = {}, user)
   attributes[:user] ||= user
   create(attributes)
  end

  def create_with_user!(attributes = {}, user)
    attributes[:user] ||= user
    create!(attributes)
  end

  def build_with_user(attributes = {}, user)
    attributes[:user] ||= user
    build(attributes)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

def create
  @review = Review.find(params[:review_id])
  @review.endorsements.create
  render json: {new_endoresement_count: @review.endorsements.count}
end


end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)

    redirect_to restaurants_path
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = 'Restaurant deleted succesfully'
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :image)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user!

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build_with_user(review_params, current_user)
    if @review.save
      redirect_to restaurants_path
    else
      if @review.errors[:user]
        redirect_to restaurants_path, alert: 'You have already reviewed this restaurant'
      else
        render :new
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

  def star_rating(rating)
    return rating unless rating.respond_to?(:round)
    remainder = (5 - rating.round)
    "★" * rating.round + "☆" * remainder
  end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta(charset="UTF-8")
    %title YelpClone
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %div.nav
      %div.grid
        %div.col-3
          %br
        %div.col-6

          %ul
            %li.logo
              = link_to "Yelp-Clone", root_path
            - if user_signed_in?
              %li.right
                = link_to "Sign Out", destroy_user_session_path, method: :delete
            - else
              %li.right
                = link_to "Sign In", new_user_session_path
              %li.right
                = link_to "Sign Up", new_user_registration_path
          %div.col-3
            %br
          %div.grid
            %div.col-3
              %br
            %div.col-6
              %div.notice
                = notice
              %div.alert
                = alert
            %div.col-3
            %br

    = yield

app/views/restaurants/edit.html.haml
%div.grid
  %div.col-3
    %br
  %div.col-6
    = form_for @restaurant, html: {multipart: true} do |f|
      = f.label :name
      = f.text_field :name
      = f.label :description
      = f.text_area :description
      = f.file_field :image
      = f.submit

  %div.col-3
    %br

app/views/restaurants/index.html.haml
%div.grid
  %div.col-3
    %br
  %div.col-6
    - if @restaurants.any?
      - @restaurants.each do |restaurant|
        %h2= link_to restaurant.name, restaurant_path(restaurant)
        %h4= restaurant.description
        %h4= image_tag restaurant.image.url(:thumb)


        %ul
          - restaurant.reviews.each do |review|
            %li
              #{review.thoughts} Average rating: #{star_rating(restaurant.average_rating)}
              = link_to "Endorse", review_endorsements_path(review), class: 'endorsements-link'
              %span.endorsements_count= review.endorsements.count
              = 'endorsement'.pluralize review.endorsements.count

        = link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant)
        = link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete
        = link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant)
    - else
      %h2 No restaurants yet!

    %h3.add_restaurant= link_to "Add a restaurant", new_restaurant_path(@restaurant)

  %div.col-3
    %br

app/views/restaurants/new.html.haml
%div.grid
  %div.col-3
    %br
  %div.col-6

    = form_for @restaurant, html: {multipart: true} do |f|
      = f.label :name
      = f.text_field :name
      = f.file_field :image
      = f.label :description
      = f.text_area :description
      = f.submit

    - if @restaurant.errors.any?
      %section#errors
        %h2
          = pluralize @restaurant.errors.count, "error"
          stopped this restaurant from being saved:
        %ul
          - @restaurant.errors.full_messages.each do |message|
            %li= message

  %div.col-3
    %br

app/views/restaurants/show.html.haml
%div.grid
  %div.col-3
    %br
  %div.col-6

    %h2= @restaurant.name
    %h4= @restaurant.description
    - @restaurant.reviews.all.each do |review|
      %p= review.thoughts
      = review.rating
    %p= link_to "Edit #{@restaurant.name}", edit_restaurant_path(@restaurant)

  %div.col-3
    %br

app/views/reviews/new.html.haml
%div.grid
  %div.col-3
    %br
  %div.col-6

    = form_for [@restaurant, @review] do |f|
      = f.label :thoughts
      = f.text_area :thoughts
      .rating
        = f.label :rating
        = f.radio_button :rating ,1
        = f.radio_button :rating ,2
        = f.radio_button :rating ,3
        = f.radio_button :rating ,4
        = f.radio_button :rating ,5
      = f.submit 'Leave Review'



  %div.col-3
    %br